CUSTOMERS = [
    # --- original 12 (tests depend on these IDs) ---
    {"id": "cus_001", "name": "Aarav Mehta", "phone": "+919810000001", "email": "aarav@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "gold", "tags": ["sneakerhead"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 4},
    {"id": "cus_002", "name": "Anaya Rao", "phone": "+919810000002", "email": "anaya@example.com", "city": "Bengaluru", "gender": "female", "loyalty_tier": "platinum", "tags": ["beauty", "premium"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 2},
    {"id": "cus_003", "name": "Kabir Singh", "phone": "+919810000003", "email": "kabir@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "silver", "tags": ["coffee", "lapsed"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 68},
    {"id": "cus_004", "name": "Mira Iyer", "phone": "+919810000004", "email": "mira@example.com", "city": "Chennai", "gender": "female", "loyalty_tier": "gold", "tags": ["ethnic", "sale"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 9},
    {"id": "cus_005", "name": "Vivaan Kapoor", "phone": "+919810000005", "email": "vivaan@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "bronze", "tags": ["new"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 40},
    {"id": "cus_006", "name": "Ira Nair", "phone": "+919810000006", "email": "ira@example.com", "city": "Kochi", "gender": "female", "loyalty_tier": "silver", "tags": ["skincare"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 13},
    {"id": "cus_007", "name": "Reyansh Shah", "phone": "+919810000007", "email": "reyansh@example.com", "city": "Ahmedabad", "gender": "male", "loyalty_tier": "gold", "tags": ["festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 7},
    {"id": "cus_008", "name": "Diya Menon", "phone": "+919810000008", "email": "diya@example.com", "city": "Pune", "gender": "female", "loyalty_tier": "platinum", "tags": ["premium", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 1},
    {"id": "cus_009", "name": "Arjun Batra", "phone": "+919810000009", "email": "arjun@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "silver", "tags": ["lapsed"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 65},
    {"id": "cus_010", "name": "Saanvi Gill", "phone": "+919810000010", "email": "saanvi@example.com", "city": "Jaipur", "gender": "female", "loyalty_tier": "gold", "tags": ["wedding", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 5},
    {"id": "cus_011", "name": "Neil Dsouza", "phone": "+919810000011", "email": "neil@example.com", "city": "Goa", "gender": "male", "loyalty_tier": "bronze", "tags": ["coffee", "new"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": True, "last_active_days_ago": 22},
    {"id": "cus_012", "name": "Tara Bose", "phone": "+919810000012", "email": "tara@example.com", "city": "Kolkata", "gender": "female", "loyalty_tier": "silver", "tags": ["beauty", "lapsed"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 74},

    # --- extended roster ---
    {"id": "cus_013", "name": "Priya Sharma", "phone": "+919810000013", "email": "priya.sharma@example.com", "city": "Mumbai", "gender": "female", "loyalty_tier": "platinum", "tags": ["premium", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 3},
    {"id": "cus_014", "name": "Rohan Verma", "phone": "+919810000014", "email": "rohan.v@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "gold", "tags": ["sneakerhead", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 11},
    {"id": "cus_015", "name": "Ishaan Gupta", "phone": "+919810000015", "email": "ishaan@example.com", "city": "Bengaluru", "gender": "male", "loyalty_tier": "silver", "tags": ["coffee", "lapsed"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 82},
    {"id": "cus_016", "name": "Nisha Patel", "phone": "+919810000016", "email": "nisha.p@example.com", "city": "Ahmedabad", "gender": "female", "loyalty_tier": "gold", "tags": ["ethnic", "festive"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 6},
    {"id": "cus_017", "name": "Aditya Nair", "phone": "+919810000017", "email": "aditya.n@example.com", "city": "Chennai", "gender": "male", "loyalty_tier": "bronze", "tags": ["new"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 31},
    {"id": "cus_018", "name": "Kavya Reddy", "phone": "+919810000018", "email": "kavya.r@example.com", "city": "Hyderabad", "gender": "female", "loyalty_tier": "platinum", "tags": ["beauty", "premium"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 2},
    {"id": "cus_019", "name": "Siddharth Malhotra", "phone": "+919810000019", "email": "sid.m@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "gold", "tags": ["festive", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 14},
    {"id": "cus_020", "name": "Ananya Kumar", "phone": "+919810000020", "email": "ananya.k@example.com", "city": "Pune", "gender": "female", "loyalty_tier": "silver", "tags": ["skincare", "sale"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 19},
    {"id": "cus_021", "name": "Vihaan Joshi", "phone": "+919810000021", "email": "vihaan.j@example.com", "city": "Jaipur", "gender": "male", "loyalty_tier": "bronze", "tags": ["lapsed"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 95},
    {"id": "cus_022", "name": "Riya Singh", "phone": "+919810000022", "email": "riya.s@example.com", "city": "Delhi", "gender": "female", "loyalty_tier": "gold", "tags": ["wedding", "premium"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 8},
    {"id": "cus_023", "name": "Aryan Mehta", "phone": "+919810000023", "email": "aryan.m@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "platinum", "tags": ["sneakerhead", "premium"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 4},
    {"id": "cus_024", "name": "Pooja Iyer", "phone": "+919810000024", "email": "pooja.i@example.com", "city": "Chennai", "gender": "female", "loyalty_tier": "silver", "tags": ["ethnic", "sale"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 28},
    {"id": "cus_025", "name": "Karan Shah", "phone": "+919810000025", "email": "karan.s@example.com", "city": "Ahmedabad", "gender": "male", "loyalty_tier": "gold", "tags": ["festive", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 16},
    {"id": "cus_026", "name": "Meera Kapoor", "phone": "+919810000026", "email": "meera.k@example.com", "city": "Mumbai", "gender": "female", "loyalty_tier": "platinum", "tags": ["beauty", "premium"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 1},
    {"id": "cus_027", "name": "Dhruv Bose", "phone": "+919810000027", "email": "dhruv.b@example.com", "city": "Kolkata", "gender": "male", "loyalty_tier": "silver", "tags": ["coffee", "lapsed"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 77},
    {"id": "cus_028", "name": "Neha Gupta", "phone": "+919810000028", "email": "neha.g@example.com", "city": "Delhi", "gender": "female", "loyalty_tier": "gold", "tags": ["sale", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 10},
    {"id": "cus_029", "name": "Yash Rao", "phone": "+919810000029", "email": "yash.r@example.com", "city": "Bengaluru", "gender": "male", "loyalty_tier": "bronze", "tags": ["new", "coffee"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 35},
    {"id": "cus_030", "name": "Siya Nair", "phone": "+919810000030", "email": "siya.n@example.com", "city": "Kochi", "gender": "female", "loyalty_tier": "silver", "tags": ["skincare", "beauty"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 17},
    {"id": "cus_031", "name": "Advait Sharma", "phone": "+919810000031", "email": "advait.s@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "gold", "tags": ["sneakerhead", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 6},
    {"id": "cus_032", "name": "Dia Patel", "phone": "+919810000032", "email": "dia.p@example.com", "city": "Ahmedabad", "gender": "female", "loyalty_tier": "silver", "tags": ["ethnic", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 23},
    {"id": "cus_033", "name": "Rishi Verma", "phone": "+919810000033", "email": "rishi.v@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "platinum", "tags": ["premium", "sneakerhead"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 3},
    {"id": "cus_034", "name": "Avni Kumar", "phone": "+919810000034", "email": "avni.k@example.com", "city": "Pune", "gender": "female", "loyalty_tier": "gold", "tags": ["beauty", "skincare"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 12},
    {"id": "cus_035", "name": "Shaan Malhotra", "phone": "+919810000035", "email": "shaan.m@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "bronze", "tags": ["lapsed"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 110},
    {"id": "cus_036", "name": "Kriti Singh", "phone": "+919810000036", "email": "kriti.s@example.com", "city": "Bengaluru", "gender": "female", "loyalty_tier": "silver", "tags": ["festive", "ethnic"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 20},
    {"id": "cus_037", "name": "Aarav Joshi", "phone": "+919810000037", "email": "aarav.j@example.com", "city": "Jaipur", "gender": "male", "loyalty_tier": "gold", "tags": ["wedding", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 9},
    {"id": "cus_038", "name": "Prachi Mehta", "phone": "+919810000038", "email": "prachi.m@example.com", "city": "Mumbai", "gender": "female", "loyalty_tier": "platinum", "tags": ["premium", "repeat", "beauty"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 2},
    {"id": "cus_039", "name": "Dev Iyer", "phone": "+919810000039", "email": "dev.i@example.com", "city": "Chennai", "gender": "male", "loyalty_tier": "silver", "tags": ["coffee", "lapsed"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": False, "rcs_opt_in": False, "last_active_days_ago": 88},
    {"id": "cus_040", "name": "Tia Shah", "phone": "+919810000040", "email": "tia.s@example.com", "city": "Hyderabad", "gender": "female", "loyalty_tier": "gold", "tags": ["beauty", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 7},
    {"id": "cus_041", "name": "Mohit Kapoor", "phone": "+919810000041", "email": "mohit.k@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "bronze", "tags": ["new"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 27},
    {"id": "cus_042", "name": "Aisha Bose", "phone": "+919810000042", "email": "aisha.b@example.com", "city": "Kolkata", "gender": "female", "loyalty_tier": "gold", "tags": ["ethnic", "sale", "festive"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 15},
    {"id": "cus_043", "name": "Kunal Nair", "phone": "+919810000043", "email": "kunal.n@example.com", "city": "Kochi", "gender": "male", "loyalty_tier": "silver", "tags": ["skincare"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 33},
    {"id": "cus_044", "name": "Sana Gupta", "phone": "+919810000044", "email": "sana.g@example.com", "city": "Delhi", "gender": "female", "loyalty_tier": "platinum", "tags": ["premium", "beauty", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 1},
    {"id": "cus_045", "name": "Raj Rao", "phone": "+919810000045", "email": "raj.r@example.com", "city": "Bengaluru", "gender": "male", "loyalty_tier": "gold", "tags": ["sneakerhead", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 10},
    {"id": "cus_046", "name": "Zara Patel", "phone": "+919810000046", "email": "zara.p@example.com", "city": "Ahmedabad", "gender": "female", "loyalty_tier": "silver", "tags": ["ethnic", "wedding"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 18},
    {"id": "cus_047", "name": "Arya Sharma", "phone": "+919810000047", "email": "arya.s@example.com", "city": "Mumbai", "gender": "female", "loyalty_tier": "gold", "tags": ["festive", "repeat"], "whatsapp_opt_in": True, "sms_opt_in": False, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 5},
    {"id": "cus_048", "name": "Nikhil Verma", "phone": "+919810000048", "email": "nikhil.v@example.com", "city": "Delhi", "gender": "male", "loyalty_tier": "bronze", "tags": ["lapsed"], "whatsapp_opt_in": False, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 120},
    {"id": "cus_049", "name": "Preethi Kumar", "phone": "+919810000049", "email": "preethi.k@example.com", "city": "Bengaluru", "gender": "female", "loyalty_tier": "silver", "tags": ["beauty", "skincare"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": False, "last_active_days_ago": 24},
    {"id": "cus_050", "name": "Ayaan Malhotra", "phone": "+919810000050", "email": "ayaan.m@example.com", "city": "Mumbai", "gender": "male", "loyalty_tier": "platinum", "tags": ["premium", "sneakerhead"], "whatsapp_opt_in": True, "sms_opt_in": True, "email_opt_in": True, "rcs_opt_in": True, "last_active_days_ago": 3},
]

ORDERS = [
    # --- original 12 ---
    {"id": "ord_001", "customer_id": "cus_001", "total": 4200, "items": ["white sneakers", "crew socks"], "channel": "store", "days_ago": 12},
    {"id": "ord_002", "customer_id": "cus_002", "total": 7800, "items": ["serum kit", "night cream"], "channel": "online", "days_ago": 16},
    {"id": "ord_003", "customer_id": "cus_003", "total": 950, "items": ["cold brew pack"], "channel": "online", "days_ago": 68},
    {"id": "ord_004", "customer_id": "cus_004", "total": 3600, "items": ["kurta set"], "channel": "store", "days_ago": 24},
    {"id": "ord_005", "customer_id": "cus_006", "total": 2200, "items": ["cleanser", "sunscreen"], "channel": "online", "days_ago": 38},
    {"id": "ord_006", "customer_id": "cus_007", "total": 5100, "items": ["festive jacket"], "channel": "online", "days_ago": 20},
    {"id": "ord_007", "customer_id": "cus_008", "total": 8900, "items": ["premium dress", "earrings"], "channel": "store", "days_ago": 8},
    {"id": "ord_008", "customer_id": "cus_009", "total": 1800, "items": ["denim shirt"], "channel": "online", "days_ago": 110},
    {"id": "ord_009", "customer_id": "cus_010", "total": 6400, "items": ["lehenga accessory set"], "channel": "store", "days_ago": 29},
    {"id": "ord_010", "customer_id": "cus_012", "total": 1400, "items": ["lip tint"], "channel": "online", "days_ago": 130},
    {"id": "ord_011", "customer_id": "cus_001", "total": 3200, "items": ["hoodie"], "channel": "online", "days_ago": 42},
    {"id": "ord_012", "customer_id": "cus_008", "total": 4100, "items": ["perfume"], "channel": "online", "days_ago": 34},

    # --- extended orders ---
    {"id": "ord_013", "customer_id": "cus_013", "total": 9200, "items": ["silk saree", "blouse piece"], "channel": "store", "days_ago": 10},
    {"id": "ord_014", "customer_id": "cus_013", "total": 5400, "items": ["party dress", "heels"], "channel": "online", "days_ago": 38},
    {"id": "ord_015", "customer_id": "cus_014", "total": 6800, "items": ["limited edition sneakers"], "channel": "online", "days_ago": 11},
    {"id": "ord_016", "customer_id": "cus_015", "total": 1100, "items": ["cold brew subscription"], "channel": "online", "days_ago": 82},
    {"id": "ord_017", "customer_id": "cus_016", "total": 4500, "items": ["anarkali suit"], "channel": "store", "days_ago": 22},
    {"id": "ord_018", "customer_id": "cus_016", "total": 3200, "items": ["dupatta set", "bangles"], "channel": "store", "days_ago": 55},
    {"id": "ord_019", "customer_id": "cus_017", "total": 1600, "items": ["basic tee pack"], "channel": "online", "days_ago": 31},
    {"id": "ord_020", "customer_id": "cus_018", "total": 8400, "items": ["luxury skincare kit"], "channel": "online", "days_ago": 9},
    {"id": "ord_021", "customer_id": "cus_018", "total": 6200, "items": ["premium moisturiser set"], "channel": "online", "days_ago": 45},
    {"id": "ord_022", "customer_id": "cus_019", "total": 7100, "items": ["sherwani", "nehru jacket"], "channel": "store", "days_ago": 14},
    {"id": "ord_023", "customer_id": "cus_020", "total": 2800, "items": ["vitamin C serum", "toner"], "channel": "online", "days_ago": 19},
    {"id": "ord_024", "customer_id": "cus_021", "total": 2100, "items": ["denim jacket"], "channel": "online", "days_ago": 95},
    {"id": "ord_025", "customer_id": "cus_022", "total": 5600, "items": ["bridal lehenga dupatta"], "channel": "store", "days_ago": 18},
    {"id": "ord_026", "customer_id": "cus_022", "total": 3900, "items": ["gold jhumkas", "maang tikka"], "channel": "store", "days_ago": 42},
    {"id": "ord_027", "customer_id": "cus_023", "total": 11200, "items": ["air max sneakers", "tracksuit"], "channel": "online", "days_ago": 7},
    {"id": "ord_028", "customer_id": "cus_023", "total": 4300, "items": ["crossbody bag"], "channel": "online", "days_ago": 30},
    {"id": "ord_029", "customer_id": "cus_024", "total": 2400, "items": ["cotton kurta set"], "channel": "store", "days_ago": 28},
    {"id": "ord_030", "customer_id": "cus_025", "total": 8600, "items": ["wedding sherwani", "stole"], "channel": "store", "days_ago": 16},
    {"id": "ord_031", "customer_id": "cus_026", "total": 12400, "items": ["platinum skincare set", "face oil"], "channel": "online", "days_ago": 5},
    {"id": "ord_032", "customer_id": "cus_026", "total": 6700, "items": ["retinol cream", "eye serum"], "channel": "online", "days_ago": 41},
    {"id": "ord_033", "customer_id": "cus_027", "total": 1300, "items": ["coffee beans 1kg"], "channel": "online", "days_ago": 77},
    {"id": "ord_034", "customer_id": "cus_028", "total": 3100, "items": ["midi dress", "belt"], "channel": "online", "days_ago": 10},
    {"id": "ord_035", "customer_id": "cus_028", "total": 2600, "items": ["blazer"], "channel": "online", "days_ago": 38},
    {"id": "ord_036", "customer_id": "cus_029", "total": 900, "items": ["cold brew sampler"], "channel": "online", "days_ago": 35},
    {"id": "ord_037", "customer_id": "cus_030", "total": 3400, "items": ["niacinamide kit", "SPF 50"], "channel": "online", "days_ago": 17},
    {"id": "ord_038", "customer_id": "cus_031", "total": 7200, "items": ["air force 1 exclusive", "socks"], "channel": "store", "days_ago": 6},
    {"id": "ord_039", "customer_id": "cus_031", "total": 4900, "items": ["limited collab hoodie"], "channel": "online", "days_ago": 44},
    {"id": "ord_040", "customer_id": "cus_032", "total": 3800, "items": ["bandhani saree"], "channel": "store", "days_ago": 23},
    {"id": "ord_041", "customer_id": "cus_033", "total": 9800, "items": ["designer sneakers", "premium cap"], "channel": "online", "days_ago": 8},
    {"id": "ord_042", "customer_id": "cus_033", "total": 7600, "items": ["leather jacket", "joggers"], "channel": "online", "days_ago": 35},
    {"id": "ord_043", "customer_id": "cus_034", "total": 5200, "items": ["glow serum bundle"], "channel": "online", "days_ago": 12},
    {"id": "ord_044", "customer_id": "cus_034", "total": 3700, "items": ["face mask set"], "channel": "online", "days_ago": 50},
    {"id": "ord_045", "customer_id": "cus_035", "total": 1700, "items": ["t-shirt 3-pack"], "channel": "online", "days_ago": 110},
    {"id": "ord_046", "customer_id": "cus_036", "total": 4100, "items": ["indo-western coord set"], "channel": "store", "days_ago": 20},
    {"id": "ord_047", "customer_id": "cus_037", "total": 9100, "items": ["groom sherwani set", "mojaris"], "channel": "store", "days_ago": 9},
    {"id": "ord_048", "customer_id": "cus_037", "total": 4400, "items": ["kurta pyjama festive"], "channel": "store", "days_ago": 45},
    {"id": "ord_049", "customer_id": "cus_038", "total": 13500, "items": ["luxury gift set", "premium oud"], "channel": "online", "days_ago": 4},
    {"id": "ord_050", "customer_id": "cus_038", "total": 8300, "items": ["platinum moisturiser", "vitamin C"], "channel": "online", "days_ago": 39},
    {"id": "ord_051", "customer_id": "cus_039", "total": 1200, "items": ["espresso pods"], "channel": "online", "days_ago": 88},
    {"id": "ord_052", "customer_id": "cus_040", "total": 6100, "items": ["festive makeup kit"], "channel": "online", "days_ago": 7},
    {"id": "ord_053", "customer_id": "cus_040", "total": 3300, "items": ["kajal set", "lip palette"], "channel": "store", "days_ago": 45},
    {"id": "ord_054", "customer_id": "cus_041", "total": 2000, "items": ["graphic tees 2-pack"], "channel": "online", "days_ago": 27},
    {"id": "ord_055", "customer_id": "cus_042", "total": 5700, "items": ["festive kurta set", "dupatta"], "channel": "store", "days_ago": 15},
    {"id": "ord_056", "customer_id": "cus_042", "total": 2900, "items": ["juttis embroidered"], "channel": "store", "days_ago": 48},
    {"id": "ord_057", "customer_id": "cus_043", "total": 2700, "items": ["hydrating face wash", "toner"], "channel": "online", "days_ago": 33},
    {"id": "ord_058", "customer_id": "cus_044", "total": 11800, "items": ["luxury perfume", "body lotion set"], "channel": "store", "days_ago": 3},
    {"id": "ord_059", "customer_id": "cus_044", "total": 7900, "items": ["premium foundation", "concealer"], "channel": "online", "days_ago": 37},
    {"id": "ord_060", "customer_id": "cus_045", "total": 8200, "items": ["jordan retro", "jersey"], "channel": "online", "days_ago": 10},
    {"id": "ord_061", "customer_id": "cus_045", "total": 3600, "items": ["running shoes"], "channel": "store", "days_ago": 52},
    {"id": "ord_062", "customer_id": "cus_046", "total": 4800, "items": ["bridal dupatta", "potli bag"], "channel": "store", "days_ago": 18},
    {"id": "ord_063", "customer_id": "cus_047", "total": 6900, "items": ["designer kurta", "festive earrings"], "channel": "online", "days_ago": 5},
    {"id": "ord_064", "customer_id": "cus_047", "total": 3500, "items": ["co-ord set"], "channel": "online", "days_ago": 38},
    {"id": "ord_065", "customer_id": "cus_048", "total": 1500, "items": ["cargo pants"], "channel": "online", "days_ago": 120},
    {"id": "ord_066", "customer_id": "cus_049", "total": 3200, "items": ["brightening serum", "eye cream"], "channel": "online", "days_ago": 24},
    {"id": "ord_067", "customer_id": "cus_050", "total": 14200, "items": ["yeezy slides", "designer backpack"], "channel": "online", "days_ago": 6},
    {"id": "ord_068", "customer_id": "cus_050", "total": 5800, "items": ["premium wallet", "belt"], "channel": "store", "days_ago": 41},
    {"id": "ord_069", "customer_id": "cus_002", "total": 4600, "items": ["retinol serum"], "channel": "online", "days_ago": 60},
    {"id": "ord_070", "customer_id": "cus_004", "total": 2800, "items": ["kota saree"], "channel": "store", "days_ago": 60},
    {"id": "ord_071", "customer_id": "cus_007", "total": 3200, "items": ["diwali gift set"], "channel": "online", "days_ago": 55},
    {"id": "ord_072", "customer_id": "cus_010", "total": 4100, "items": ["silk dupatta"], "channel": "store", "days_ago": 72},
    {"id": "ord_073", "customer_id": "cus_014", "total": 3900, "items": ["sneaker cleaning kit"], "channel": "online", "days_ago": 55},
    {"id": "ord_074", "customer_id": "cus_019", "total": 2700, "items": ["kurta pajama"], "channel": "store", "days_ago": 60},
    {"id": "ord_075", "customer_id": "cus_023", "total": 2200, "items": ["socks bundle"], "channel": "online", "days_ago": 65},
    {"id": "ord_076", "customer_id": "cus_025", "total": 5100, "items": ["ethnic jacket"], "channel": "store", "days_ago": 52},
    {"id": "ord_077", "customer_id": "cus_031", "total": 2900, "items": ["cap collection"], "channel": "online", "days_ago": 70},
    {"id": "ord_078", "customer_id": "cus_033", "total": 3100, "items": ["sneaker organiser"], "channel": "online", "days_ago": 62},
    {"id": "ord_079", "customer_id": "cus_038", "total": 4700, "items": ["mini perfume set"], "channel": "online", "days_ago": 80},
    {"id": "ord_080", "customer_id": "cus_044", "total": 3400, "items": ["blush palette"], "channel": "online", "days_ago": 70},
    {"id": "ord_081", "customer_id": "cus_045", "total": 2100, "items": ["gym bag"], "channel": "online", "days_ago": 88},
    {"id": "ord_082", "customer_id": "cus_050", "total": 3300, "items": ["caps 2-pack"], "channel": "store", "days_ago": 77},
    {"id": "ord_083", "customer_id": "cus_026", "total": 3900, "items": ["face oil", "serum"], "channel": "online", "days_ago": 75},
    {"id": "ord_084", "customer_id": "cus_013", "total": 4200, "items": ["evening gown"], "channel": "store", "days_ago": 65},
    {"id": "ord_085", "customer_id": "cus_022", "total": 2800, "items": ["silver anklets"], "channel": "store", "days_ago": 65},
    {"id": "ord_086", "customer_id": "cus_040", "total": 2400, "items": ["highlighter duo"], "channel": "online", "days_ago": 68},
    {"id": "ord_087", "customer_id": "cus_042", "total": 1900, "items": ["kolhapuri sandals"], "channel": "store", "days_ago": 75},
    {"id": "ord_088", "customer_id": "cus_047", "total": 2600, "items": ["festive blouse"], "channel": "store", "days_ago": 80},
    {"id": "ord_089", "customer_id": "cus_016", "total": 2100, "items": ["churidar set"], "channel": "store", "days_ago": 90},
    {"id": "ord_090", "customer_id": "cus_028", "total": 1800, "items": ["sunglasses"], "channel": "online", "days_ago": 58},
]

# ---------------------------------------------------------------------------
# Saved Segments
# ---------------------------------------------------------------------------
SEGMENTS = [
    {
        "id": "seg_seed_lapsed_sms",
        "name": "Inactive SMS Shoppers",
        "rules": {"channel": "sms", "min_last_order_days_ago": 60},
    },
    {
        "id": "seg_seed_vip_whatsapp",
        "name": "VIP WhatsApp Shoppers",
        "rules": {"channel": "whatsapp", "min_lifetime_value": 7000},
    },
    {
        "id": "seg_seed_festive_email",
        "name": "Festive Email Buyers",
        "rules": {"channel": "email", "tag": "festive"},
    },
    {
        "id": "seg_seed_recent_whatsapp",
        "name": "Recent WhatsApp Buyers",
        "rules": {"channel": "whatsapp", "max_last_order_days_ago": 30},
    },
    {
        "id": "seg_seed_delhi_whatsapp",
        "name": "Delhi WhatsApp Shoppers",
        "rules": {"channel": "whatsapp", "city": "Delhi"},
    },
]

# ---------------------------------------------------------------------------
# Campaigns
# ---------------------------------------------------------------------------
# statuses: draft | approved | queued | sending | completed
CAMPAIGNS = [
    {
        "id": "cmp_seed_001",
        "name": "Lapsed Shopper Comeback",
        "goal": "Win back shoppers who have not purchased in 60+ days with a personalized SMS offer.",
        "channel": "sms",
        "segment_rules": {"channel": "sms", "min_last_order_days_ago": 60},
        "message_template": "Hi {{name}}, we miss you! It's been a while since your last order. Come back with 20% off your next purchase — use code COMEBACK20 today. 🛍️",
        "status": "completed",
        "approved_plan": {
            "campaign_name": "Lapsed Shopper Comeback",
            "goal": "Win back shoppers who have not purchased in 60+ days with a personalized SMS offer.",
            "recommended_channel": "sms",
            "recommended_segment": {"rules": {"channel": "sms", "min_last_order_days_ago": 60}, "reasoning": "Targeting 9 lapsed shoppers via SMS (highest opt-in rate for this segment)."},
            "message_variants": [{"label": "direct", "template": "Hi {{name}}, we miss you! 20% off with code COMEBACK20."}],
            "risk_notes": ["Requires marketer approval before send.", "Segment limited to SMS opt-ins only."],
            "expected_audience_size": 9,
        },
        "days_ago_created": 18,
        "days_ago_approved": 17,
    },
    {
        "id": "cmp_seed_002",
        "name": "VIP Platinum Early Access",
        "goal": "Give platinum-tier shoppers early access to the new premium collection via WhatsApp.",
        "channel": "whatsapp",
        "segment_rules": {"channel": "whatsapp", "min_lifetime_value": 7000},
        "message_template": "Hi {{name}}, as one of our platinum members you get exclusive early access to our new collection before anyone else. Tap to shop 👑",
        "status": "completed",
        "approved_plan": {
            "campaign_name": "VIP Platinum Early Access",
            "goal": "Give platinum-tier shoppers early access to the new premium collection via WhatsApp.",
            "recommended_channel": "whatsapp",
            "recommended_segment": {"rules": {"channel": "whatsapp", "min_lifetime_value": 7000}, "reasoning": "High-value customers (LTV ≥ ₹7,000) who are WhatsApp opted-in tend to convert at 3× the average rate."},
            "message_variants": [{"label": "direct", "template": "Hi {{name}}, exclusive early access just for you 👑"}],
            "risk_notes": ["Requires marketer approval before send.", "Only opted-in platinum customers included."],
            "expected_audience_size": 10,
        },
        "days_ago_created": 11,
        "days_ago_approved": 10,
    },
    {
        "id": "cmp_seed_003",
        "name": "Festive Season Activation",
        "goal": "Drive festive purchases from shoppers tagged as festive buyers via email.",
        "channel": "email",
        "segment_rules": {"channel": "email", "tag": "festive"},
        "message_template": "Hi {{name}}, your festive edit is here! We've handpicked looks for the season — shop your personalized collection now and celebrate in style. ✨",
        "status": "completed",
        "approved_plan": {
            "campaign_name": "Festive Season Activation",
            "goal": "Drive festive purchases from shoppers tagged as festive buyers via email.",
            "recommended_channel": "email",
            "recommended_segment": {"rules": {"channel": "email", "tag": "festive"}, "reasoning": "Festive-tagged customers showed 2.4× higher open rates in previous seasonal campaigns."},
            "message_variants": [{"label": "festive", "template": "Hi {{name}}, your festive edit is here! ✨"}],
            "risk_notes": ["Requires marketer approval before send.", "Email volume may affect deliverability — send in batches."],
            "expected_audience_size": 12,
        },
        "days_ago_created": 6,
        "days_ago_approved": 5,
    },
    {
        "id": "cmp_seed_004",
        "name": "Recent Buyer New Arrivals",
        "goal": "Show recent buyers (last 30 days) the new arrivals drop via WhatsApp.",
        "channel": "whatsapp",
        "segment_rules": {"channel": "whatsapp", "max_last_order_days_ago": 30},
        "message_template": "Hi {{name}}, new arrivals just dropped and we picked some looks we think you'll love based on your last order. Be the first to shop 🔥",
        "status": "approved",
        "approved_plan": {},
        "days_ago_created": 2,
        "days_ago_approved": 1,
    },
    {
        "id": "cmp_seed_005",
        "name": "Summer Sale — Delhi Shoppers",
        "goal": "Drive summer sale conversions from Delhi-based customers via WhatsApp.",
        "channel": "whatsapp",
        "segment_rules": {"channel": "whatsapp", "city": "Delhi"},
        "message_template": "Hi {{name}}, the Summer Sale is live in Delhi! Up to 40% off your favourite brands — tap to explore your personalised sale picks. 🌞",
        "status": "draft",
        "approved_plan": {},
        "days_ago_created": 1,
        "days_ago_approved": None,
    },
]

# ---------------------------------------------------------------------------
# Communications (messages sent per campaign per customer)
# status progression per customer: queued → sent → delivered → opened / clicked / converted / failed
# ---------------------------------------------------------------------------

def _msg(campaign_id, customer_id, channel, name, phone, email, template, status, revenue=0):
    msg = template.replace("{{name}}", name.split()[0])
    return {
        "id": f"msg_{campaign_id}_{customer_id}",
        "campaign_id": campaign_id,
        "customer_id": customer_id,
        "channel": channel,
        "recipient": {"name": name, "phone": phone, "email": email},
        "message": msg,
        "status": status,
        "attributed_revenue": revenue,
    }


# Campaign 1 — Lapsed Shopper Comeback (SMS, completed)
# Target: lapsed 60+ days with sms_opt_in
_C1 = "cmp_seed_001"
COMMUNICATIONS = [
    _msg(_C1, "cus_003", "sms", "Kabir Singh",    "+919810000003", "kabir@example.com",  "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "converted", 1850),
    _msg(_C1, "cus_009", "sms", "Arjun Batra",    "+919810000009", "arjun@example.com",  "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "clicked"),
    _msg(_C1, "cus_012", "sms", "Tara Bose",      "+919810000012", "tara@example.com",   "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "delivered"),
    _msg(_C1, "cus_015", "sms", "Ishaan Gupta",   "+919810000015", "ishaan@example.com", "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "converted", 2100),
    _msg(_C1, "cus_021", "sms", "Vihaan Joshi",   "+919810000021", "vihaan.j@example.com","Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "clicked"),
    _msg(_C1, "cus_027", "sms", "Dhruv Bose",     "+919810000027", "dhruv.b@example.com", "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "delivered"),
    _msg(_C1, "cus_035", "sms", "Shaan Malhotra", "+919810000035", "shaan.m@example.com", "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "failed"),
    _msg(_C1, "cus_039", "sms", "Dev Iyer",       "+919810000039", "dev.i@example.com",   "Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "delivered"),
    _msg(_C1, "cus_048", "sms", "Nikhil Verma",   "+919810000048", "nikhil.v@example.com","Hi {{name}}, we miss you! 20% off with code COMEBACK20.", "sent"),
]

# Campaign 2 — VIP Platinum Early Access (WhatsApp, completed)
_C2 = "cmp_seed_002"
COMMUNICATIONS += [
    _msg(_C2, "cus_002", "whatsapp", "Anaya Rao",       "+919810000002", "anaya@example.com",     "Hi {{name}}, exclusive early access just for you 👑", "converted", 7800),
    _msg(_C2, "cus_008", "whatsapp", "Diya Menon",      "+919810000008", "diya@example.com",      "Hi {{name}}, exclusive early access just for you 👑", "converted", 4100),
    _msg(_C2, "cus_013", "whatsapp", "Priya Sharma",    "+919810000013", "priya.sharma@example.com","Hi {{name}}, exclusive early access just for you 👑", "clicked"),
    _msg(_C2, "cus_018", "whatsapp", "Kavya Reddy",     "+919810000018", "kavya.r@example.com",   "Hi {{name}}, exclusive early access just for you 👑", "clicked"),
    _msg(_C2, "cus_023", "whatsapp", "Aryan Mehta",     "+919810000023", "aryan.m@example.com",   "Hi {{name}}, exclusive early access just for you 👑", "converted", 11200),
    _msg(_C2, "cus_026", "whatsapp", "Meera Kapoor",    "+919810000026", "meera.k@example.com",   "Hi {{name}}, exclusive early access just for you 👑", "converted", 12400),
    _msg(_C2, "cus_033", "whatsapp", "Rishi Verma",     "+919810000033", "rishi.v@example.com",   "Hi {{name}}, exclusive early access just for you 👑", "clicked"),
    _msg(_C2, "cus_038", "whatsapp", "Prachi Mehta",    "+919810000038", "prachi.m@example.com",  "Hi {{name}}, exclusive early access just for you 👑", "converted", 13500),
    _msg(_C2, "cus_044", "whatsapp", "Sana Gupta",      "+919810000044", "sana.g@example.com",    "Hi {{name}}, exclusive early access just for you 👑", "clicked"),
    _msg(_C2, "cus_050", "whatsapp", "Ayaan Malhotra",  "+919810000050", "ayaan.m@example.com",   "Hi {{name}}, exclusive early access just for you 👑", "converted", 14200),
]

# Campaign 3 — Festive Season Activation (email, completed)
_C3 = "cmp_seed_003"
COMMUNICATIONS += [
    _msg(_C3, "cus_007", "email", "Reyansh Shah",  "+919810000007", "reyansh@example.com",   "Hi {{name}}, your festive edit is here! ✨", "converted", 5100),
    _msg(_C3, "cus_010", "email", "Saanvi Gill",   "+919810000010", "saanvi@example.com",    "Hi {{name}}, your festive edit is here! ✨", "clicked"),
    _msg(_C3, "cus_013", "email", "Priya Sharma",  "+919810000013", "priya.sharma@example.com","Hi {{name}}, your festive edit is here! ✨", "clicked"),
    _msg(_C3, "cus_016", "email", "Nisha Patel",   "+919810000016", "nisha.p@example.com",   "Hi {{name}}, your festive edit is here! ✨", "converted", 4500),
    _msg(_C3, "cus_019", "email", "Siddharth Malhotra", "+919810000019", "sid.m@example.com", "Hi {{name}}, your festive edit is here! ✨", "delivered"),
    _msg(_C3, "cus_022", "email", "Riya Singh",    "+919810000022", "riya.s@example.com",    "Hi {{name}}, your festive edit is here! ✨", "converted", 5600),
    _msg(_C3, "cus_025", "email", "Karan Shah",    "+919810000025", "karan.s@example.com",   "Hi {{name}}, your festive edit is here! ✨", "clicked"),
    _msg(_C3, "cus_037", "email", "Aarav Joshi",   "+919810000037", "aarav.j@example.com",   "Hi {{name}}, your festive edit is here! ✨", "converted", 9100),
    _msg(_C3, "cus_040", "email", "Tia Shah",      "+919810000040", "tia.s@example.com",     "Hi {{name}}, your festive edit is here! ✨", "delivered"),
    _msg(_C3, "cus_042", "email", "Aisha Bose",    "+919810000042", "aisha.b@example.com",   "Hi {{name}}, your festive edit is here! ✨", "clicked"),
    _msg(_C3, "cus_047", "email", "Arya Sharma",   "+919810000047", "arya.s@example.com",    "Hi {{name}}, your festive edit is here! ✨", "converted", 6900),
    _msg(_C3, "cus_002", "email", "Anaya Rao",     "+919810000002", "anaya@example.com",     "Hi {{name}}, your festive edit is here! ✨", "delivered"),
]
